// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package db

import (
	"context"
)

const activateNewsletterUserByEmail = `-- name: ActivateNewsletterUserByEmail :exec
UPDATE users
SET newsletter = true, updated_at = NOW()
WHERE email = $1
RETURNING id, sub, email, email_verified, picture, name, surname, full_name, newsletter, admin, active, created_at, updated_at
`

func (q *Queries) ActivateNewsletterUserByEmail(ctx context.Context, email string) error {
	_, err := q.db.ExecContext(ctx, activateNewsletterUserByEmail, email)
	return err
}

const activateNewsletterUserById = `-- name: ActivateNewsletterUserById :exec
UPDATE users
SET newsletter = true, updated_at = NOW()
WHERE id = $1
RETURNING id, sub, email, email_verified, picture, name, surname, full_name, newsletter, admin, active, created_at, updated_at
`

func (q *Queries) ActivateNewsletterUserById(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, activateNewsletterUserById, id)
	return err
}

const activateNewsletterUserBySub = `-- name: ActivateNewsletterUserBySub :exec
UPDATE users
SET newsletter = true, updated_at = NOW()
WHERE sub = $1
RETURNING id, sub, email, email_verified, picture, name, surname, full_name, newsletter, admin, active, created_at, updated_at
`

func (q *Queries) ActivateNewsletterUserBySub(ctx context.Context, sub string) error {
	_, err := q.db.ExecContext(ctx, activateNewsletterUserBySub, sub)
	return err
}

const activateUserByEmail = `-- name: ActivateUserByEmail :exec
UPDATE users
SET active = true, updated_at = NOW()
WHERE email = $1
RETURNING id, sub, email, email_verified, picture, name, surname, full_name, newsletter, admin, active, created_at, updated_at
`

func (q *Queries) ActivateUserByEmail(ctx context.Context, email string) error {
	_, err := q.db.ExecContext(ctx, activateUserByEmail, email)
	return err
}

const activateUserById = `-- name: ActivateUserById :exec
UPDATE users
SET active = true, updated_at = NOW()
WHERE id = $1
RETURNING id, sub, email, email_verified, picture, name, surname, full_name, newsletter, admin, active, created_at, updated_at
`

func (q *Queries) ActivateUserById(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, activateUserById, id)
	return err
}

const activateUserBySub = `-- name: ActivateUserBySub :exec
UPDATE users
SET active = true, updated_at = NOW()
WHERE sub = $1
RETURNING id, sub, email, email_verified, picture, name, surname, full_name, newsletter, admin, active, created_at, updated_at
`

func (q *Queries) ActivateUserBySub(ctx context.Context, sub string) error {
	_, err := q.db.ExecContext(ctx, activateUserBySub, sub)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, sub, email_verified, name, full_name, picture)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, sub, email, email_verified, picture, name, surname, full_name, newsletter, admin, active, created_at, updated_at
`

type CreateUserParams struct {
	Email         string
	Sub           string
	EmailVerified bool
	Name          string
	FullName      string
	Picture       string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Email,
		arg.Sub,
		arg.EmailVerified,
		arg.Name,
		arg.FullName,
		arg.Picture,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Sub,
		&i.Email,
		&i.EmailVerified,
		&i.Picture,
		&i.Name,
		&i.Surname,
		&i.FullName,
		&i.Newsletter,
		&i.Admin,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateNewsletterUserByEmail = `-- name: DeactivateNewsletterUserByEmail :exec
UPDATE users
SET newsletter = false, updated_at = NOW()
WHERE email = $1
RETURNING id, sub, email, email_verified, picture, name, surname, full_name, newsletter, admin, active, created_at, updated_at
`

func (q *Queries) DeactivateNewsletterUserByEmail(ctx context.Context, email string) error {
	_, err := q.db.ExecContext(ctx, deactivateNewsletterUserByEmail, email)
	return err
}

const deactivateNewsletterUserById = `-- name: DeactivateNewsletterUserById :exec
UPDATE users
SET newsletter = false, updated_at = NOW()
WHERE id = $1
RETURNING id, sub, email, email_verified, picture, name, surname, full_name, newsletter, admin, active, created_at, updated_at
`

func (q *Queries) DeactivateNewsletterUserById(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deactivateNewsletterUserById, id)
	return err
}

const deactivateNewsletterUserBySub = `-- name: DeactivateNewsletterUserBySub :exec
UPDATE users
SET newsletter = false, updated_at = NOW()
WHERE sub = $1
RETURNING id, sub, email, email_verified, picture, name, surname, full_name, newsletter, admin, active, created_at, updated_at
`

func (q *Queries) DeactivateNewsletterUserBySub(ctx context.Context, sub string) error {
	_, err := q.db.ExecContext(ctx, deactivateNewsletterUserBySub, sub)
	return err
}

const deactivateUserByEmail = `-- name: DeactivateUserByEmail :exec
UPDATE users
SET active = false, updated_at = NOW()
WHERE email = $1
RETURNING id, sub, email, email_verified, picture, name, surname, full_name, newsletter, admin, active, created_at, updated_at
`

func (q *Queries) DeactivateUserByEmail(ctx context.Context, email string) error {
	_, err := q.db.ExecContext(ctx, deactivateUserByEmail, email)
	return err
}

const deactivateUserById = `-- name: DeactivateUserById :exec
UPDATE users
SET active = false, updated_at = NOW()
WHERE id = $1
RETURNING id, sub, email, email_verified, picture, name, surname, full_name, newsletter, admin, active, created_at, updated_at
`

func (q *Queries) DeactivateUserById(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deactivateUserById, id)
	return err
}

const deactivateUserBySub = `-- name: DeactivateUserBySub :exec
UPDATE users
SET active = false, updated_at = NOW()
WHERE sub = $1
RETURNING id, sub, email, email_verified, picture, name, surname, full_name, newsletter, admin, active, created_at, updated_at
`

func (q *Queries) DeactivateUserBySub(ctx context.Context, sub string) error {
	_, err := q.db.ExecContext(ctx, deactivateUserBySub, sub)
	return err
}

const deleteUserByEmail = `-- name: DeleteUserByEmail :exec
DELETE FROM users WHERE email = $1
`

func (q *Queries) DeleteUserByEmail(ctx context.Context, email string) error {
	_, err := q.db.ExecContext(ctx, deleteUserByEmail, email)
	return err
}

const deleteUserById = `-- name: DeleteUserById :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUserById(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteUserById, id)
	return err
}

const deleteUserBySub = `-- name: DeleteUserBySub :exec
DELETE FROM users WHERE sub = $1
`

func (q *Queries) DeleteUserBySub(ctx context.Context, sub string) error {
	_, err := q.db.ExecContext(ctx, deleteUserBySub, sub)
	return err
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT id, sub, email, email_verified, picture, name, surname, full_name, newsletter, admin, active, created_at, updated_at FROM users LIMIT $1 OFFSET $2
`

type GetAllUsersParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) GetAllUsers(ctx context.Context, arg GetAllUsersParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getAllUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Sub,
			&i.Email,
			&i.EmailVerified,
			&i.Picture,
			&i.Name,
			&i.Surname,
			&i.FullName,
			&i.Newsletter,
			&i.Admin,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, sub, email, email_verified, picture, name, surname, full_name, newsletter, admin, active, created_at, updated_at FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Sub,
		&i.Email,
		&i.EmailVerified,
		&i.Picture,
		&i.Name,
		&i.Surname,
		&i.FullName,
		&i.Newsletter,
		&i.Admin,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, sub, email, email_verified, picture, name, surname, full_name, newsletter, admin, active, created_at, updated_at FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserById(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Sub,
		&i.Email,
		&i.EmailVerified,
		&i.Picture,
		&i.Name,
		&i.Surname,
		&i.FullName,
		&i.Newsletter,
		&i.Admin,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserBySub = `-- name: GetUserBySub :one
SELECT id, sub, email, email_verified, picture, name, surname, full_name, newsletter, admin, active, created_at, updated_at FROM users
WHERE sub = $1 LIMIT 1
`

func (q *Queries) GetUserBySub(ctx context.Context, sub string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserBySub, sub)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Sub,
		&i.Email,
		&i.EmailVerified,
		&i.Picture,
		&i.Name,
		&i.Surname,
		&i.FullName,
		&i.Newsletter,
		&i.Admin,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAdminById = `-- name: UpdateAdminById :exec
UPDATE users
SET admin = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, sub, email, email_verified, picture, name, surname, full_name, newsletter, admin, active, created_at, updated_at
`

type UpdateAdminByIdParams struct {
	ID    int32
	Admin bool
}

func (q *Queries) UpdateAdminById(ctx context.Context, arg UpdateAdminByIdParams) error {
	_, err := q.db.ExecContext(ctx, updateAdminById, arg.ID, arg.Admin)
	return err
}

const updateToAdminByEmail = `-- name: UpdateToAdminByEmail :exec
UPDATE users
SET admin = $2, updated_at = NOW()
WHERE email = $1
RETURNING id, sub, email, email_verified, picture, name, surname, full_name, newsletter, admin, active, created_at, updated_at
`

type UpdateToAdminByEmailParams struct {
	Email string
	Admin bool
}

func (q *Queries) UpdateToAdminByEmail(ctx context.Context, arg UpdateToAdminByEmailParams) error {
	_, err := q.db.ExecContext(ctx, updateToAdminByEmail, arg.Email, arg.Admin)
	return err
}

const updateToAdminBySub = `-- name: UpdateToAdminBySub :exec
UPDATE users
SET admin = $2, updated_at = NOW()
WHERE sub = $1
RETURNING id, sub, email, email_verified, picture, name, surname, full_name, newsletter, admin, active, created_at, updated_at
`

type UpdateToAdminBySubParams struct {
	Sub   string
	Admin bool
}

func (q *Queries) UpdateToAdminBySub(ctx context.Context, arg UpdateToAdminBySubParams) error {
	_, err := q.db.ExecContext(ctx, updateToAdminBySub, arg.Sub, arg.Admin)
	return err
}

const updateUserByEmail = `-- name: UpdateUserByEmail :exec
UPDATE users
SET name = $2, full_name = $3, picture = $4, updated_at = NOW()
WHERE email = $1
RETURNING id, sub, email, email_verified, picture, name, surname, full_name, newsletter, admin, active, created_at, updated_at
`

type UpdateUserByEmailParams struct {
	Email    string
	Name     string
	FullName string
	Picture  string
}

func (q *Queries) UpdateUserByEmail(ctx context.Context, arg UpdateUserByEmailParams) error {
	_, err := q.db.ExecContext(ctx, updateUserByEmail,
		arg.Email,
		arg.Name,
		arg.FullName,
		arg.Picture,
	)
	return err
}

const updateUserById = `-- name: UpdateUserById :exec
UPDATE users
SET name = $2, full_name = $3, picture = $4, email_verified = $5, updated_at = NOW()
WHERE id = $1
RETURNING id, sub, email, email_verified, picture, name, surname, full_name, newsletter, admin, active, created_at, updated_at
`

type UpdateUserByIdParams struct {
	ID            int32
	Name          string
	FullName      string
	Picture       string
	EmailVerified bool
}

func (q *Queries) UpdateUserById(ctx context.Context, arg UpdateUserByIdParams) error {
	_, err := q.db.ExecContext(ctx, updateUserById,
		arg.ID,
		arg.Name,
		arg.FullName,
		arg.Picture,
		arg.EmailVerified,
	)
	return err
}

const updateUserBySub = `-- name: UpdateUserBySub :exec
UPDATE users
SET name = $2, full_name = $3, picture = $4, updated_at = NOW()
WHERE sub = $1
RETURNING id, sub, email, email_verified, picture, name, surname, full_name, newsletter, admin, active, created_at, updated_at
`

type UpdateUserBySubParams struct {
	Sub      string
	Name     string
	FullName string
	Picture  string
}

func (q *Queries) UpdateUserBySub(ctx context.Context, arg UpdateUserBySubParams) error {
	_, err := q.db.ExecContext(ctx, updateUserBySub,
		arg.Sub,
		arg.Name,
		arg.FullName,
		arg.Picture,
	)
	return err
}

const updateUserPicture = `-- name: UpdateUserPicture :exec
UPDATE users
SET picture = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, sub, email, email_verified, picture, name, surname, full_name, newsletter, admin, active, created_at, updated_at
`

type UpdateUserPictureParams struct {
	ID      int32
	Picture string
}

func (q *Queries) UpdateUserPicture(ctx context.Context, arg UpdateUserPictureParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPicture, arg.ID, arg.Picture)
	return err
}
