import furg from "/furg_logo.jpg";
import raquel from "/itec2_logo.jpg";
import byte from "/bytejr_logo.jpg";
import itec from "/itec2_logo.jpg";
import lamsa from "/lamsa_logo.svg";
import petc3 from "/petc3_logo.jpg";

export const EN_INFOS = {
  infos: {
    name: 'Romulo de Moraes',
    position: 'Software Developer',
    bio: 'I am an Information Systems student with a strong interest in web development. On my GitHub, I stay active with personal and group projects with various goals and themes, using technologies similar to those mentioned in the experiences below. I am communicative, enjoy writing and teaching about what I learn, and I love challenges.',
  },
  contact: {
    address: 'Rio Grande, Brazil',
    email: 'romulotg12@gmail.com',
    linkedin: 'https://www.linkedin.com/in/romulo-de-moraes-918793258/',
    github: 'https://www.github.com/romulodm',
  },
  education: [
    {
      school: 'Federal University of Rio Grande - FURG',
      url: 'https://www.furg.br',
      icon: furg,
      location: 'Rio Grande, Brazil',
      degree: 'Undergraduate',
      major: 'Information Systems',
      start: 'April 2022',
      end: 'Present',
    }
  ],
  experience: [
    {
      company: 'Byte Jr.',
      url: 'https://www.linkedin.com/company/bytejr/',
      icon: byte,
      location: 'Rio Grande, Brazil',
      contract: 'Volunteer',
      position: 'President',
      start: 'March 2024',
      end: 'Present',
      about: 'I am working on restructuring the junior enterprise Byte Jr. together with Professor Dr. Luciano Maciel Ribeiro and colleagues from C3 - FURG. We are continuing projects that were on hold and improving the company’s financial and administrative health.',
      skills: [
        'People Management',
        'Administration',
      ],
    },
    {
      company: 'iTEC - Plena',
      url: 'https://www.linkedin.com/company/raquel-menopausa/?originalSubdomain=br',
      icon: raquel,
      location: 'Rio Grande, Brazil',
      contract: 'Research Fellowship',
      position: 'Back-end Developer',
      start: 'April 2024',
      end: 'Present',
      about: 'I am working on the backend development of an application focused on women’s health. We are using microservices architecture with NestJS, working together with the computer vision, artificial intelligence, and frontend teams.',
      skills: [
        'NestJS',
        'Jest',
        'ESLint',
        'Prisma',
        'PostgreSQL',
        'Azure Dev-Ops',
        'Docker',
        'Terraform',
        'AWS',
      ],
    },
    {
      company: 'iTEC - MexTec',
      url: 'https://itecfurg.org/?p=4101',
      icon: itec,
      location: 'Rio Grande, Brazil',
      contract: 'Research Fellowship',
      position: 'Full-stack Developer',
      start: 'December 2023',
      end: 'July 2024',
      about: 'I worked on developing a web system that processes and displays information on a control panel. These data were collected from various sensors and transmitted via ESP32. Additionally, I was involved in integration with the teams responsible for maintaining and operating the sensors.',
      description: [
        'Development of a web system using React, with authentication, real-time data display, access levels...',
        'Backend development with Express, building some modules and adapting them for the frontend.',
        'Communication via ESP32 using HTTP and MQTT.',
        'Project infrastructure management, checking logs and performance.',
      ],
      skills: [
        'React',
        'Tailwind CSS',
        'Material UI',
        'React-Flow',
        'Redux',
        'Express',
        'Mongoose',
        'JWT',
        'Socket.io',
        'MQTT',
        'ESP32',
        'LoRa',
      ],
    },
    {
      company: 'EMAJ',
      url: 'https://www.furg.br/comunidade/escritorio-modelo-assessoria-juridica',
      icon: furg,
      location: 'Rio Grande, Brazil',
      contract: 'Volunteer',
      position: 'Full-stack Developer',
      start: 'August 2023',
      end: 'December 2023',
      about: 'EMAJ is a legal advisory office at FURG run by law students and professors, serving the general public. I worked on developing a web system to assist EMAJ members in their daily activities. The idea came from Professor André Prisco, coordinator of the Information Systems course, and was part of the thesis of three Computer Engineering students.',
      skills: [
        'React',
        'Tailwind CSS',
        'Material UI',
        'Redux',
        'Express',
        'JWT',
        'Multer',
        'AWS S3',
        'Sequelize',
        'PostgresSQL',
      ],
    },
    {
      company: 'LAMSA',
      url: 'https://www.linkedin.com/company/lamsa-furg/',
      icon: lamsa,
      location: 'Rio Grande, Brazil',
      contract: 'Volunteer',
      position: 'Unity Developer',
      start: 'May 2023',
      end: 'November 2023',
      about: 'I assisted in researching and developing a virtual reality game using the Unity platform, addressing the theme of ocean preservation and aiming to educate children about the importance of conserving marine species.',
      skills: [
        'C#',
        'Unity',
      ],
    },
    {
      company: 'PETC3',
      url: 'https://www.instagram.com/petc3furg/',
      icon: petc3,
      location: 'Rio Grande, Brazil',
      contract: 'Research Fellowship',
      position: 'Researcher',
      start: 'June 2022',
      end: 'December 2023',
      about: 'PET is a government program aimed at groups of students who demonstrate potential, aiming to promote extracurricular activities under the guidance of a tutor professor. This project was my first experience within FURG and was essential for improving some soft skills - mainly communication and teamwork.',
      description: [
        'Participation in the LEGO subproject, where we taught computational thinking to students in the region’s schools using Scratch and LEGO Mindstorms.',
        'Participation in the PETCode subproject, where we created applications to assist PETC3’s internal demands, posted on Instagram about programming, and studied together.',
        'Organization of events for the students of C3 - FURG.'
      ],
      skills: [
        'HTML',
        'CSS',
        'JavaScript',
        'Python',
        'Flask',
        'React',
        'Express',
        'JWT',
        'PostgresSQL',
        'MongoDB',
      ],
    },
  ],
  languages: [
    {
      name: 'Portuguese',
      level: 'C2',
      color: 'blue',
      native: true,
    },
    {
      name: 'English',
      level: 'B1',
      color: 'yellow',
    }
  ],
};
