import furg from "/furg_logo.jpg";
import raquel from "/itec2_logo.jpg";
import byte from "/bytejr_logo.jpg";
import itec from "/itec2_logo.jpg";
import lamsa from "/lamsa_logo.svg";
import petc3 from "/petc3_logo.jpg";

export const PT_INFOS = {
  infos: {
    name: 'Romulo de Moraes',
    position: 'Desenvolvedor de Software',
    bio: 'Sou estudante de Sistemas de Informação e me interesso bastante por desenvolvimento web. No meu GitHub estou me mantendo ativo com projetos pessoais e em grupo com objetivos e temas variados, utilizando tecnologias parecidas com as que são citadas nas experiências abaixo. Sou comunicativo, gosto de escrever e ensinar sobre aquilo que aprendo e curto desafios.',
  },
  contact: {
    address: 'Rio Grande, Brasil',
    email: 'romulotg12@gmail.com',
    linkedin: 'https://www.linkedin.com/in/romulodm',
    github: 'https://www.github.com/romulodm',
  },
  education: [
    {
      school: 'Universidade Federal do Rio Grande - FURG',
      url: 'https://www.furg.br',
      icon: furg,
      location: 'Rio Grande, Brasil',
      degree: 'Graduação',
      major: 'Sistemas de Informação',
      start: 'Abril 2022',
      end: 'Atualmente',
    }
  ],
  experience: [
    {
      company: 'Byte Jr.',
      url: 'https://www.linkedin.com/company/bytejr/',
      icon: byte,
      location: 'Rio Grande, Brasil',
      contract: 'Voluntário',
      position: 'Presidente',
      start: 'Março 2024',
      end: 'Atualmente',
      about: 'Estou atuando na reestruturação da empresa júnior Byte Jr. juntamente com o professor Dr. Luciano Maciel Ribeiro e colegas do C3 - FURG. Estamos dando continuidade a projetos que estavam parados e melhorando a saúde financeira e administrativa da empresa.',
      skills: [
        'Gestão de Pessoas',
        'Administração',
      ],
    },
    {
      company: 'iTEC - Plena',
      url: 'https://www.linkedin.com/company/raquel-menopausa/?originalSubdomain=br',
      icon: raquel,
      location: 'Rio Grande, Brasil',
      contract: 'Bolsista',
      position: 'Desenvolvedor Back-end',
      start: 'Abril 2024',
      end: 'Atualmente',
      about: 'Estou trabalhando no desenvolvimento do backend de um aplicativo voltado para a saúde feminina. Estamos usando arquitetura de microsserviços com NestJS, atuando em conjunto com os times de visão computacional, inteligência artificial e frontend.',
      skills: [
        'NestJS',
        'Jest',
        'ESLint',
        'Prisma',
        'PostgreSQL',
        'Azure Dev-Ops',
        'Docker',
        'Terraform',
        'AWS',
      ],
    },
    {
      company: 'iTEC - MexTec',
      url: 'https://itecfurg.org/?p=4101',
      icon: itec,
      location: 'Rio Grande, Brasil',
      contract: 'Bolsista',
      position: 'Desenvolvedor Full-stack',
      start: 'Dezembro 2023',
      end: 'Julho 2024',
      about: 'Trabalhei no desenvolvimento de um sistema web que trata e exibe informações em um painel de controle. Esses dados eram coletados de diversos sensores e transmitidos via ESP32. Além disso, estive envolvido na integração com as equipes responsáveis pela manutenção e operação dos sensores.',
      description: [
        'Desenvolvimento de um sistema web usando React, com autenticação, exibição dos dados em tempo real, níveis de acesso...',
        'Desenvolvimento backend com Express, construção de alguns módulos e adaptação para o frontend.',
        'Comunicação via ESP32 usando HTTP e MQTT.',
        'Cuidado com a infraestrutura do projeto, verificando logs e desempenho.',
      ],
      skills: [
        'React',
        'Tailwind CSS',
        'Material UI',
        'React-Flow',
        'Redux',
        'Express',
        'Mongoose',
        'JWT',
        'Socket.io',
        'MQTT',
        'ESP32',
        'LoRa',
      ],
    },
    {
      company: 'EMAJ',
      url: 'https://www.furg.br/comunidade/escritorio-modelo-assessoria-juridica',
      icon: furg,
      location: 'Rio Grande, Brasil',
      contract: 'Voluntário',
      position: 'Desenvolvedor Full-stack',
      start: 'Agosto 2023',
      end: 'Dezembro 2023',
      about: 'O EMAJ é um escritório da FURG de alunos e professores do curso de direito da universidade, que atendem o público em geral. Atuei no desenvolvimento de um sistema web para auxiliar os membros do EMAJ em suas atividades diárias. A ideia partiu do professor André Prisco, coordenador do curso de Sistemas de Informação, e fez parte do TCC de três alunos de Engenharia de Computação.',
      skills: [
        'React',
        'Tailwind CSS',
        'Material UI',
        'Redux',
        'Express',
        'JWT',
        'Multer',
        'AWS S3',
        'Sequelize',
        'PostgresSQL',
      ],
    },
    {
      company: 'LAMSA',
      url: 'https://www.linkedin.com/company/lamsa-furg/',
      icon: lamsa,
      location: 'Rio Grande, Brasil',
      contract: 'Voluntário',
      position: 'Desenvolvedor Unity',
      start: 'Maio 2023',
      end: 'Novembro 2023',
      about: 'Auxiliei na pesquisa e desenvolvimento de um jogo de realidade virtual utilizando a plataforma Unity, que abordava a temática da preservação dos oceanos e tinha como objetivo educar as crianças sobre a importância da conservação das espécies marinhas.',
      skills: [
        'C#',
        'Unity',
      ],
    },
    {
      company: 'PETC3',
      url: 'https://www.instagram.com/petc3furg/',
      icon: petc3,
      location: 'Rio Grande, Brasil',
      contract: 'Bolsista',
      position: 'Bolsista',
      start: 'Junho 2022',
      end: 'Dezembro 2023',
      about: 'O PET é um programa governamental destinado a grupos de alunos que demonstrem potencial, que visa o fomento da realização de atividades extracurriculares sob a orientação de um professor tutor. Esse projeto foi a minha primeira experiência dentro da FURG e foi fundamental para aprimorar algumas soft skills - principalmente comunicação e trabalho em equipe.',
      description: [
        'Participação do subprojeto LEGO, onde ensinávamos pensamento computacional para alunos das escolas da região usando Scratch e LEGO Mindstorms.',
        'Participação do subprojeto PETCode, onde criávamos aplicações para auxiliar nas demandas internas do PETC3, fazíamos postagens no Instagram sobre programação e estudávamos de forma conjunta.',
        'Organização de eventos voltados para os alunos do C3 - FURG.'
      ],
      skills: [
        'HTML',
        'CSS',
        'JavaScript',
        'Python',
        'Flask',
        'React',
        'Express',
        'JWT',
        'PostgresSQL',
        'MongoDB',
      ],
    },
  ],
  languages: [
    {
      name: 'Português',
      level: 'C2',
      color: 'blue',
      native: true,
    },
    {
      name: 'Inglês',
      level: 'B1',
      color: 'yellow',
    }
  ],
};
