// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: comments.sql

package db

import (
	"context"
	"database/sql"
)

const createComment = `-- name: CreateComment :one
INSERT INTO comments (content, user_id, post_id, created_at)
VALUES ($1, $2, $3, NOW())
RETURNING id, content, replies_count, likes_count, created_at, updated_at, user_id, post_id
`

type CreateCommentParams struct {
	Content string
	UserID  int32
	PostID  int32
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRowContext(ctx, createComment, arg.Content, arg.UserID, arg.PostID)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.Content,
		&i.RepliesCount,
		&i.LikesCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.PostID,
	)
	return i, err
}

const createCommentLike = `-- name: CreateCommentLike :one
INSERT INTO comments_likes (user_id, comment_id, created_at)
VALUES ($1, $2, NOW())
RETURNING id, created_at, user_id, comment_id
`

type CreateCommentLikeParams struct {
	UserID    sql.NullInt32
	CommentID sql.NullInt32
}

func (q *Queries) CreateCommentLike(ctx context.Context, arg CreateCommentLikeParams) (CommentsLike, error) {
	row := q.db.QueryRowContext(ctx, createCommentLike, arg.UserID, arg.CommentID)
	var i CommentsLike
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UserID,
		&i.CommentID,
	)
	return i, err
}

const createCommentReply = `-- name: CreateCommentReply :one
INSERT INTO comments_reply (content, user_id, post_id, comment_id, created_at)
VALUES ($1, $2, $3, $4, NOW())
RETURNING id, content, likes_count, created_at, updated_at, user_id, post_id, comment_id
`

type CreateCommentReplyParams struct {
	Content   string
	UserID    sql.NullInt32
	PostID    sql.NullInt32
	CommentID sql.NullInt32
}

func (q *Queries) CreateCommentReply(ctx context.Context, arg CreateCommentReplyParams) (CommentsReply, error) {
	row := q.db.QueryRowContext(ctx, createCommentReply,
		arg.Content,
		arg.UserID,
		arg.PostID,
		arg.CommentID,
	)
	var i CommentsReply
	err := row.Scan(
		&i.ID,
		&i.Content,
		&i.LikesCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.PostID,
		&i.CommentID,
	)
	return i, err
}

const createCommentReplyLike = `-- name: CreateCommentReplyLike :one
INSERT INTO comments_replies_likes (user_id, comment_reply_id, created_at)
VALUES ($1, $2, NOW())
RETURNING id, created_at, user_id, comment_reply_id
`

type CreateCommentReplyLikeParams struct {
	UserID         sql.NullInt32
	CommentReplyID sql.NullInt32
}

func (q *Queries) CreateCommentReplyLike(ctx context.Context, arg CreateCommentReplyLikeParams) (CommentsRepliesLike, error) {
	row := q.db.QueryRowContext(ctx, createCommentReplyLike, arg.UserID, arg.CommentReplyID)
	var i CommentsRepliesLike
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UserID,
		&i.CommentReplyID,
	)
	return i, err
}

const decrementCommentLikes = `-- name: DecrementCommentLikes :exec
UPDATE comments
SET likes_count = likes_count - 1
WHERE id = $1
`

func (q *Queries) DecrementCommentLikes(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, decrementCommentLikes, id)
	return err
}

const decrementCommentReplyLikes = `-- name: DecrementCommentReplyLikes :exec
UPDATE comments_reply
SET likes_count = likes_count - 1
WHERE id = $1
`

func (q *Queries) DecrementCommentReplyLikes(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, decrementCommentReplyLikes, id)
	return err
}

const deleteComment = `-- name: DeleteComment :exec
DELETE FROM comments
WHERE id = $1
RETURNING id, content, replies_count, likes_count, created_at, updated_at, user_id, post_id
`

func (q *Queries) DeleteComment(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteComment, id)
	return err
}

const deleteCommentLike = `-- name: DeleteCommentLike :exec
DELETE FROM comments_likes
WHERE id = $1
RETURNING id, created_at, user_id, comment_id
`

func (q *Queries) DeleteCommentLike(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteCommentLike, id)
	return err
}

const deleteCommentReply = `-- name: DeleteCommentReply :exec
DELETE FROM comments_reply
WHERE id = $1
RETURNING id, content, likes_count, created_at, updated_at, user_id, post_id, comment_id
`

func (q *Queries) DeleteCommentReply(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteCommentReply, id)
	return err
}

const deleteCommentReplyLike = `-- name: DeleteCommentReplyLike :exec
DELETE FROM comments_replies_likes
WHERE id = $1
RETURNING id, created_at, user_id, comment_reply_id
`

func (q *Queries) DeleteCommentReplyLike(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteCommentReplyLike, id)
	return err
}

const getAllCommentsByPostId = `-- name: GetAllCommentsByPostId :many
SELECT id, content, replies_count, likes_count, created_at, updated_at, user_id, post_id FROM comments
WHERE post_id = $1
`

func (q *Queries) GetAllCommentsByPostId(ctx context.Context, postID sql.NullInt32) ([]Comment, error) {
	rows, err := q.db.QueryContext(ctx, getAllCommentsByPostId, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Comment
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.RepliesCount,
			&i.LikesCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.PostID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCommentLikesByCommentId = `-- name: GetCommentLikesByCommentId :many
SELECT id, created_at, user_id, comment_id FROM comments_likes
WHERE comment_id = $1
`

func (q *Queries) GetCommentLikesByCommentId(ctx context.Context, commentID sql.NullInt32) ([]CommentsLike, error) {
	rows, err := q.db.QueryContext(ctx, getCommentLikesByCommentId, commentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CommentsLike
	for rows.Next() {
		var i CommentsLike
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UserID,
			&i.CommentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCommentLikesByUserId = `-- name: GetCommentLikesByUserId :one
SELECT id, created_at, user_id, comment_id FROM comments_likes
WHERE user_id = $1
`

func (q *Queries) GetCommentLikesByUserId(ctx context.Context, userID sql.NullInt32) (CommentsLike, error) {
	row := q.db.QueryRowContext(ctx, getCommentLikesByUserId, userID)
	var i CommentsLike
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UserID,
		&i.CommentID,
	)
	return i, err
}

const getCommentRepliesByCommentId = `-- name: GetCommentRepliesByCommentId :many
SELECT id, content, likes_count, created_at, updated_at, user_id, post_id, comment_id FROM comments_reply
WHERE comment_id = $1
`

func (q *Queries) GetCommentRepliesByCommentId(ctx context.Context, commentID sql.NullInt32) ([]CommentsReply, error) {
	rows, err := q.db.QueryContext(ctx, getCommentRepliesByCommentId, commentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CommentsReply
	for rows.Next() {
		var i CommentsReply
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.LikesCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.PostID,
			&i.CommentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCommentRepliesById = `-- name: GetCommentRepliesById :many
SELECT id, content, likes_count, created_at, updated_at, user_id, post_id, comment_id FROM comments_reply
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetCommentRepliesById(ctx context.Context, id int32) ([]CommentsReply, error) {
	rows, err := q.db.QueryContext(ctx, getCommentRepliesById, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CommentsReply
	for rows.Next() {
		var i CommentsReply
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.LikesCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.PostID,
			&i.CommentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCommentReplyLikesByReplyId = `-- name: GetCommentReplyLikesByReplyId :many
SELECT id, created_at, user_id, comment_reply_id FROM comments_replies_likes
WHERE comment_reply_id = $1
`

func (q *Queries) GetCommentReplyLikesByReplyId(ctx context.Context, commentReplyID sql.NullInt32) ([]CommentsRepliesLike, error) {
	rows, err := q.db.QueryContext(ctx, getCommentReplyLikesByReplyId, commentReplyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CommentsRepliesLike
	for rows.Next() {
		var i CommentsRepliesLike
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UserID,
			&i.CommentReplyID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCommentReplyLikesByUserId = `-- name: GetCommentReplyLikesByUserId :many
SELECT id, created_at, user_id, comment_reply_id FROM comments_replies_likes
WHERE user_id = $1
`

func (q *Queries) GetCommentReplyLikesByUserId(ctx context.Context, userID sql.NullInt32) ([]CommentsRepliesLike, error) {
	rows, err := q.db.QueryContext(ctx, getCommentReplyLikesByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CommentsRepliesLike
	for rows.Next() {
		var i CommentsRepliesLike
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UserID,
			&i.CommentReplyID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCommentsByPostAndUserId = `-- name: GetCommentsByPostAndUserId :many
SELECT id, content, replies_count, likes_count, created_at, updated_at, user_id, post_id FROM comments
WHERE post_id = $1 AND user_id = $2
`

type GetCommentsByPostAndUserIdParams struct {
	PostID sql.NullInt32
	UserID sql.NullInt32
}

func (q *Queries) GetCommentsByPostAndUserId(ctx context.Context, arg GetCommentsByPostAndUserIdParams) ([]Comment, error) {
	rows, err := q.db.QueryContext(ctx, getCommentsByPostAndUserId, arg.PostID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Comment
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.RepliesCount,
			&i.LikesCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.PostID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCommentsByPostId = `-- name: GetCommentsByPostId :many
SELECT id, content, replies_count, likes_count, created_at, updated_at, user_id, post_id FROM comments
WHERE post_id = $1
`

func (q *Queries) GetCommentsByPostId(ctx context.Context, postID sql.NullInt32) ([]Comment, error) {
	rows, err := q.db.QueryContext(ctx, getCommentsByPostId, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Comment
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.RepliesCount,
			&i.LikesCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.PostID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCommentsByUserId = `-- name: GetCommentsByUserId :many
SELECT id, content, replies_count, likes_count, created_at, updated_at, user_id, post_id FROM comments
WHERE user_id = $1
`

func (q *Queries) GetCommentsByUserId(ctx context.Context, userID sql.NullInt32) ([]Comment, error) {
	rows, err := q.db.QueryContext(ctx, getCommentsByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Comment
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.RepliesCount,
			&i.LikesCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.PostID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementCommentLikes = `-- name: IncrementCommentLikes :exec
UPDATE comments
SET likes_count = likes_count + 1
WHERE id = $1
`

func (q *Queries) IncrementCommentLikes(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, incrementCommentLikes, id)
	return err
}

const incrementCommentReplyLikes = `-- name: IncrementCommentReplyLikes :exec
UPDATE comments_reply
SET likes_count = likes_count + 1
WHERE id = $1
`

func (q *Queries) IncrementCommentReplyLikes(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, incrementCommentReplyLikes, id)
	return err
}

const updateComment = `-- name: UpdateComment :exec
UPDATE comments
SET content = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, content, replies_count, likes_count, created_at, updated_at, user_id, post_id
`

type UpdateCommentParams struct {
	ID      int32
	Content string
}

func (q *Queries) UpdateComment(ctx context.Context, arg UpdateCommentParams) error {
	_, err := q.db.ExecContext(ctx, updateComment, arg.ID, arg.Content)
	return err
}

const updateCommentReply = `-- name: UpdateCommentReply :exec
UPDATE comments_reply
SET content = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, content, likes_count, created_at, updated_at, user_id, post_id, comment_id
`

type UpdateCommentReplyParams struct {
	ID      int32
	Content string
}

func (q *Queries) UpdateCommentReply(ctx context.Context, arg UpdateCommentReplyParams) error {
	_, err := q.db.ExecContext(ctx, updateCommentReply, arg.ID, arg.Content)
	return err
}
