// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: likes.sql

package db

import (
	"context"
	"database/sql"
)

const createLike = `-- name: CreateLike :one
INSERT INTO likes (user_id, post_id, created_at)
VALUES ($1, $2, NOW())
RETURNING id, created_at, user_id, post_id
`

type CreateLikeParams struct {
	UserID sql.NullInt32
	PostID sql.NullInt32
}

func (q *Queries) CreateLike(ctx context.Context, arg CreateLikeParams) (Like, error) {
	row := q.db.QueryRowContext(ctx, createLike, arg.UserID, arg.PostID)
	var i Like
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UserID,
		&i.PostID,
	)
	return i, err
}

const deleteLike = `-- name: DeleteLike :exec
DELETE FROM likes
WHERE id = $1
RETURNING id, created_at, user_id, post_id
`

func (q *Queries) DeleteLike(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteLike, id)
	return err
}

const getLikesById = `-- name: GetLikesById :many
SELECT id, created_at, user_id, post_id FROM likes
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetLikesById(ctx context.Context, id int32) ([]Like, error) {
	rows, err := q.db.QueryContext(ctx, getLikesById, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Like
	for rows.Next() {
		var i Like
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UserID,
			&i.PostID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLikesByPostId = `-- name: GetLikesByPostId :many
SELECT id, created_at, user_id, post_id FROM likes
WHERE post_id = $1
`

func (q *Queries) GetLikesByPostId(ctx context.Context, postID sql.NullInt32) ([]Like, error) {
	rows, err := q.db.QueryContext(ctx, getLikesByPostId, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Like
	for rows.Next() {
		var i Like
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UserID,
			&i.PostID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLikesByUserId = `-- name: GetLikesByUserId :many
SELECT id, created_at, user_id, post_id FROM likes
WHERE user_id = $1
`

func (q *Queries) GetLikesByUserId(ctx context.Context, userID sql.NullInt32) ([]Like, error) {
	rows, err := q.db.QueryContext(ctx, getLikesByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Like
	for rows.Next() {
		var i Like
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UserID,
			&i.PostID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
