// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"time"
)

type Comment struct {
	ID           int32
	Content      string
	RepliesCount int32
	LikesCount   int32
	CreatedAt    time.Time
	UpdatedAt    time.Time
	UserID       int32
	PostID       int32
}

type CommentsLike struct {
	ID        int32
	CreatedAt time.Time
	UserID    int32
	CommentID int32
}

type CommentsRepliesLike struct {
	ID             int32
	CreatedAt      time.Time
	UserID         int32
	CommentReplyID int32
}

type CommentsReply struct {
	ID         int32
	Content    string
	LikesCount int32
	CreatedAt  time.Time
	UpdatedAt  time.Time
	UserID     int32
	PostID     int32
	CommentID  int32
}

type Like struct {
	ID        int32
	CreatedAt time.Time
	UserID    int32
	PostID    int32
}

type Post struct {
	ID            int32
	Slug          string
	Link          string
	ViewsCount    int32
	LikesCount    int32
	CommentsCount int32
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type User struct {
	ID            int32
	Sub           string
	Email         string
	EmailVerified bool
	Picture       string
	Name          string
	Surname       string
	FullName      string
	Newsletter    bool
	Admin         bool
	Active        bool
	CreatedAt     time.Time
	UpdatedAt     time.Time
}
