// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
	"time"
)

type Comment struct {
	ID           int32
	Content      sql.NullString
	RepliesCount sql.NullInt32
	LikesCount   sql.NullInt32
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
	UserID       sql.NullInt32
	PostID       sql.NullInt32
}

type CommentsLike struct {
	ID        int32
	CreatedAt time.Time
	UserID    sql.NullInt32
	CommentID sql.NullInt32
}

type CommentsRepliesLike struct {
	ID             int32
	CreatedAt      time.Time
	UserID         sql.NullInt32
	CommentReplyID sql.NullInt32
}

type CommentsReply struct {
	ID         int32
	Content    sql.NullString
	LikesCount sql.NullInt32
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
	UserID     sql.NullInt32
	PostID     sql.NullInt32
	CommentID  sql.NullInt32
}

type Like struct {
	ID        int32
	CreatedAt sql.NullTime
	UserID    sql.NullInt32
	PostID    sql.NullInt32
}

type Post struct {
	ID            int32
	Slug          string
	Link          sql.NullString
	ViewsCount    sql.NullInt32
	LikesCount    sql.NullInt32
	CommentsCount sql.NullInt32
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
}

type User struct {
	ID            int32
	Sub           string
	Email         string
	EmailVerified bool
	Picture       string
	Name          string
	FullName      string
	Admin         bool
	Active        sql.NullBool
	CreatedAt     time.Time
	UpdatedAt     sql.NullTime
}
