// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: posts.sql

package db

import (
	"context"
)

const createPost = `-- name: CreatePost :one
INSERT INTO posts (slug, link)
VALUES ($1, $2)
RETURNING id, slug, link, views_count, likes_count, comments_count, created_at, updated_at
`

type CreatePostParams struct {
	Slug string
	Link string
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, createPost, arg.Slug, arg.Link)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Link,
		&i.ViewsCount,
		&i.LikesCount,
		&i.CommentsCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const decrementPostComments = `-- name: DecrementPostComments :exec
UPDATE posts
SET comments_count = comments_count - 1
WHERE id = $1 AND comments_count > 0
`

func (q *Queries) DecrementPostComments(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, decrementPostComments, id)
	return err
}

const decrementPostLikes = `-- name: DecrementPostLikes :exec
UPDATE posts
SET likes_count = likes_count - 1
WHERE id = $1 AND likes_count > 0
`

func (q *Queries) DecrementPostLikes(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, decrementPostLikes, id)
	return err
}

const deletePost = `-- name: DeletePost :exec
DELETE FROM posts WHERE id = $1
`

func (q *Queries) DeletePost(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deletePost, id)
	return err
}

const getAllPosts = `-- name: GetAllPosts :many
SELECT id, slug, link, views_count, likes_count, comments_count, created_at, updated_at FROM posts LIMIT $1 OFFSET $2
`

type GetAllPostsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) GetAllPosts(ctx context.Context, arg GetAllPostsParams) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, getAllPosts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Link,
			&i.ViewsCount,
			&i.LikesCount,
			&i.CommentsCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPostById = `-- name: GetPostById :one
SELECT id, slug, link, views_count, likes_count, comments_count, created_at, updated_at FROM posts
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPostById(ctx context.Context, id int32) (Post, error) {
	row := q.db.QueryRowContext(ctx, getPostById, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Link,
		&i.ViewsCount,
		&i.LikesCount,
		&i.CommentsCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPostBySlug = `-- name: GetPostBySlug :one
SELECT id, slug, link, views_count, likes_count, comments_count, created_at, updated_at FROM posts
WHERE slug = $1 LIMIT 1
`

func (q *Queries) GetPostBySlug(ctx context.Context, slug string) (Post, error) {
	row := q.db.QueryRowContext(ctx, getPostBySlug, slug)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Link,
		&i.ViewsCount,
		&i.LikesCount,
		&i.CommentsCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementPostComments = `-- name: IncrementPostComments :exec
UPDATE posts
SET comments_count = comments_count + 1
WHERE id = $1
`

func (q *Queries) IncrementPostComments(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, incrementPostComments, id)
	return err
}

const incrementPostLikes = `-- name: IncrementPostLikes :exec
UPDATE posts
SET likes_count = likes_count + 1
WHERE id = $1
`

func (q *Queries) IncrementPostLikes(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, incrementPostLikes, id)
	return err
}

const incrementPostViews = `-- name: IncrementPostViews :exec
UPDATE posts
SET views_count = views_count + 1
WHERE id = $1
`

func (q *Queries) IncrementPostViews(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, incrementPostViews, id)
	return err
}

const updateLinkById = `-- name: UpdateLinkById :exec
UPDATE posts
SET link = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, slug, link, views_count, likes_count, comments_count, created_at, updated_at
`

type UpdateLinkByIdParams struct {
	ID   int32
	Link string
}

func (q *Queries) UpdateLinkById(ctx context.Context, arg UpdateLinkByIdParams) error {
	_, err := q.db.ExecContext(ctx, updateLinkById, arg.ID, arg.Link)
	return err
}

const updateSlugById = `-- name: UpdateSlugById :exec
UPDATE posts
SET slug = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, slug, link, views_count, likes_count, comments_count, created_at, updated_at
`

type UpdateSlugByIdParams struct {
	ID   int32
	Slug string
}

func (q *Queries) UpdateSlugById(ctx context.Context, arg UpdateSlugByIdParams) error {
	_, err := q.db.ExecContext(ctx, updateSlugById, arg.ID, arg.Slug)
	return err
}
