// Module declarations for static image imports (`import x from './a.png'`).
//
// Next ships these in next/image-types/global, and normally they arrive through
// next-env.d.ts. That file is generated by `next dev` / `next build` and is
// gitignored, so on a fresh CI checkout it does not exist yet when
// `npm run typecheck` runs (the build comes later): every image import then
// fails with TS2307 even though the same code type-checks locally, where a
// previous dev run left next-env.d.ts behind. Referencing the types from a
// committed file removes the dependency on that generated one.
/// <reference types="next/image-types/global" />
