#!/usr/bin/env bash
#
# Regenerates nginx/conf.d/cloudflare-real-ip.inc from Cloudflare's official
# published IP ranges.
#
# WHY THIS MATTERS:
# Cloudflare's ranges change from time to time. If the local copy goes stale,
# nginx stops trusting the CF-Connecting-IP header from those ranges and falls
# back to the edge IP as the client address. Every visitor behind that range
# then shares one rate-limit bucket — and nothing errors out, so the only
# symptom is legitimate users getting 429s.
#
# Usage:
#   ./nginx/scripts/update-cloudflare-ips.sh
#   docker exec romulodm-nginx nginx -t && docker exec romulodm-nginx nginx -s reload
#
set -euo pipefail

OUTPUT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/conf.d/cloudflare-real-ip.inc"
TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

{
  echo "# Generated by nginx/scripts/update-cloudflare-ips.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "# Do not edit by hand."
  echo "#"
  echo "# Tells nginx: for connections coming from these ranges, take the real"
  echo "# client IP from the CF-Connecting-IP header instead of the socket."
  echo
  echo "real_ip_header    CF-Connecting-IP;"
  echo "# No-op with CF-Connecting-IP (which holds a single address); kept so"
  echo "# the file stays correct if the header is ever switched to X-Forwarded-For."
  echo "real_ip_recursive on;"
  echo
  echo "# IPv4"
} > "$TMP"

curl -fsSL https://www.cloudflare.com/ips-v4 \
  | grep -E '^[0-9]' \
  | sed 's|^|set_real_ip_from |; s|$|;|' >> "$TMP"

echo >> "$TMP"
echo "# IPv6" >> "$TMP"

curl -fsSL https://www.cloudflare.com/ips-v6 \
  | grep -E '^[0-9a-fA-F]' \
  | sed 's|^|set_real_ip_from |; s|$|;|' >> "$TMP"

# Only replace the file if the download looks plausible. Guards against a
# silently truncated response wiping the working config.
if [ "$(grep -c set_real_ip_from "$TMP")" -lt 10 ]; then
  echo "ERROR: fewer ranges than expected; aborting without touching $OUTPUT" >&2
  exit 1
fi

mv "$TMP" "$OUTPUT"
# mktemp creates files as 0600. nginx runs as a different user inside the
# container, so make it world-readable or the include fails at startup.
chmod 0644 "$OUTPUT"
trap - EXIT

echo "OK: $OUTPUT updated ($(grep -c set_real_ip_from "$OUTPUT") ranges)."
echo "Now run: docker exec romulodm-nginx nginx -t && docker exec romulodm-nginx nginx -s reload"
